[package]
name = "bevy_water"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.17.3"
bevy_egui = "0.38.1"

# Optimize dependencies in debug mode for performance
[profile.dev.package."*"]
opt-level = 3
